CodeSamples/formal/litmus: Add pointer cast for klitmus7 compat on Linux v5.8
On v5.8, "make" under klitmus/ ends up in error:

    In file included from ./include/linux/export.h:43,
                     from ./include/linux/linkage.h:7,
                     from ./include/linux/kernel.h:8,
                     from ./include/linux/list.h:9,
                     from ./include/linux/module.h:12,
                     from [...]/CodeSamples/fromal/herd/klitmus/litmus030.c:11:
    [...]/CodeSamples/formal/herd/klitmus/litmus030.c: In function 'code0':
    ./include/linux/compiler.h:297:30: error: assignment to 'int * volatile'
    from incomatible pointer type 'int **' [-Werror=incompatible-pointer-types]
      297 |  *(volatile typeof(x) *)&(x) = (val);   \
          |                              ^

    ./include/linux/compiler.h:303:2: note: in expansion of macro '__WRITE_ONCE'
      303 |  __WRITE_ONCE(x, val);    \
          |  ^~~~~~~~~~~~

    [...]/CodeSamples/formal/herd/klitmus/litmus030.c:363:2: note: in expansion
    of macro 'WRITE_ONCE'
      363 |  WRITE_ONCE(*x, x);
          |  ^~~~~~~~~~

    cc1: some warnings being treated as errors

The warning is enabled by the Linux kernel side commit a5460b5e5fb8
("READ_ONCE: Simplify implementations of {READ,WRITE}_ONCE()").

In the corresponding litmus test, x is declared as "int **x".
The WRITE_ONCE is assigning self address to the pointer.

Adding a pointer cast in the WRITE_ONCE() macro:

    WRITE_ONCE(*x, (int*)x);

makes the compiler happy.

NOTE1: These litmus tests are converted from those under CodeSamples/formal/litmus.
NOTE2: They are not presented as code snippets in perfbook text at the moment.

Signed-off-by: Akira Yokosawa <akiyks@gmail.com>